language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO_VERSION=1.4.22
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.11
  - DJANGO_VERSION=1.8.10
  - DJANGO_VERSION=1.9.3
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -e .
  - pip install -r .travis-requirements.txt
script:
  coverage run --source=pagseguro testapp/manage.py test pagseguro
after_success:
  coveralls
matrix:
  exclude:
    - python: "3.4"
      env: DJANGO_VERSION=1.4.22
