language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - DJANGO_VERSION=1.4.13
  - DJANGO_VERSION=1.5.8
  - DJANGO_VERSION=1.6.5
  - DJANGO_VERSION=1.7.1
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -e .
  - pip install -r .travis-requirements.txt
script:
  coverage run --source=pagseguro testapp/manage.py test pagseguro
after_success:
  coveralls
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO_VERSION=1.7.1
    - python: "3.2"
      env: DJANGO_VERSION=1.4.13
    - python: "3.3"
      env: DJANGO_VERSION=1.4.13
    - python: "3.4"
      env: DJANGO_VERSION=1.4.13
