language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - DJANGO_VERSION=1.3
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
install:
  - pip install -q Django==$DJANGO_VERSION --use-mirrors
  - pip install -e . --use-mirrors
  - pip install -r .travis-requirements.txt --use-mirrors
script:
  coverage run --source=pagseguro testapp/manage.py test pagseguro
after_success:
  coveralls
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO_VERSION=1.3
    - python: "3.2"
      env: DJANGO_VERSION=1.4
    - python: "3.3"
      env: DJANGO_VERSION=1.3
    - python: "3.3"
      env: DJANGO_VERSION=1.4
    - python: "3.4"
      env: DJANGO_VERSION=1.3
    - python: "3.4"
      env: DJANGO_VERSION=1.4
